language: python
sudo: required
dist: xenial
python: "3.7"

install:
  - "pip install pipenv"
  - "pipenv install --dev"
services:
  - "postgresql"
before_script:
  - "psql -c 'create database travis_ci_test;' -U postgres"
script:
  - "python manage.py makemigrations"
  - "python manage.py migrate"
  - "python manage.py test"
