# Use containers instead of full VMs for faster startup.
sudo: false

language: python
python:
  - "3.6"
services:
  - mysql
env:
  - DJANGO=2.1 DB=msql
install:
  - "pip install -r requirements/development.txt"
before_script:
  - mysql -e 'create database test;' -u root
script:
  - "python manage.py test"
