# Use containers instead of full VMs for faster startup.
sudo: false

language: python
python:
  - "3.6"
install:
  - pip install -r requirements/production.txt
services:
  - postgresql
before_script:
  - psql -c 'create database excsystem;' -U admin
script:
  - python manage.py test
