# Use containers instead of full VMs for faster startup.
sudo: false

language: python
python:
  - "3.6"
services:
  - postgresql
install:
  - pip install -r requirements/production.txt
before_script:
  - psql -c "CREATE DATABASE testdb;" -U postgres
  - psql -c "CREATE USER myuser WITH PASSWORD 'password';" -U postgres
  - psql -c "ALTER USER myuser CREATEDB;" -U postgres
  - python manage.py migrate
script:
  - python manage.py test
addons:
  postgresql: "9.6"