language: python
sudo: required
dist: xenial
python: 3.8

install:
  - pip install pipenv
  - pipenv install
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE travis_ci_test;" -U postgres
  - psql -c "CREATE USER foo WITH PASSWORD 'bar';" -U postgres
  - psql -c "ALTER ROLE foo CREATEDB;" -U postgres
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python helper_scripts/build_permissions.py
  - python manage.py test --keepdb
