language: python
sudo: required
dist: xenial
python: 3.7

install:
  - pip install pipenv
  - pipenv install --dev
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE travis_ci_test;" -U postgres
  - psql -c "CREATE USER foo WITH PASSWORD 'bar';" -U postgres
  - psql -c "ALTER ROLE foo CREATEDB;" -U postgres
  - export PYTHONPATH="/usr/local/lib/python3.7/dist-packages"
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python helper_scripts/build_basic_data.py
  - python manage.py test --keepdb
