version: '3.5'

services:
  db:
    image: postgres:9.5
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  web:
    build: .
    entrypoint: ./run_app.sh
    volumes:
      - .:/code
    ports:
      - 80:8000
    depends_on:
      - db