# Generated by Django 2.0.7 on 2018-09-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='title',
            field=models.CharField(max_length=140),
        ),
    ]
