# Generated by Django 2.1.2 on 2018-10-10 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gear',
            old_name='geartype',
            new_name='gear_type',
        ),
    ]
