# Generated by Django 2.1.2 on 2018-11-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MemberRFIDCheck",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rfid_checked", models.CharField(max_length=12)),
                ("was_valid", models.BooleanField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("message", models.CharField(max_length=100)),
            ],
        )
    ]
